version: '3'
services:
    starsea:
        container_name: starsea
        image: starsea-jupyter
        build: ./ss-jupyter
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/notebooks
            - ./scripts:/home/jovyan/scripts
            - ./data/.cache:/home/jovyan/.cache
        entrypoint:  
            - /bin/sh
            - -c
            - |
                jt -t onedork -f roboto -fs 14 -nfs 14 -tfs 14 -ofs 11
                jupyter lab --allow-root --ip=0.0.0.0 --no-browser
        restart: always
        environment:
            - JUPYTER_ENABLE_LAB=true
            - JUPYTER_TOKEN=starsea
        stdin_open: true
        tty: true
        extra_hosts:
            - "github.com:192.30.253.113"
            - "assets-cdn.github.com:185.199.108.153"
            - "github.global.ssl.fastly.net:151.101.185.194"
        networks:
            - starsea-net

networks:
    starsea-net:
        driver: bridge