version: '3'
services:
    starsea:
        container_name: starsea
        image: starsea-jupyter
        build: ./ss-jupyter
        # runtime: runsc
        ports:
            - "8888:8888"
        volumes:
            - ./data:/home/jovyan/models
            - ./ss-jupyter:/home/jovyan/ss
            - ./data/.cache:/home/jovyan/.cache
            # - ./data/fonts:/usr/share/fonts
            # - ./pip.conf:/etc/pip.conf
        # command: ""
        #   pip install -r /home/jovyan/ss/requirements.txt
        entrypoint:  
            - /bin/sh
            - -c
            - |
              jt -t onedork -f roboto -fs 14 -nfs 14 -tfs 14 -ofs 11
              jupyter lab --allow-root --ip=0.0.0.0 --no-browser
        restart: always
        environment:
            - JUPYTER_ENABLE_LAB=true
            - JUPYTER_TOKEN=starsea
        stdin_open: true
        tty: true
        extra_hosts:
            - "github.com:192.30.253.113"
            - "assets-cdn.github.com:185.199.108.153"
            - "github.global.ssl.fastly.net:151.101.185.194"
    # redis:
    #     container_name: redis
    #     image: redis:alpine
    #     restart: always
    #     command: redis-server --requirepass mypasswd
    #     ports :
    #         - 6379:6379