version: '3'
services:
    starsea:
        image: starsea-jupyter
        build: ./ss-jupyter
        ports:
            - "8888:8888"
        volumes:
            - ./data:/home
        restart: always
