version: '3'
services:
    starsea:
        container_name: starsea
        image: starsea-jupyter
        build: ./ss-jupyter
        # runtime: runsc
        ports:
            - "8888:8888"
        volumes:
            - ./data:/home/jovyan/models
            - ./ss-jupyter:/home/jovyan/ss
            - ./data/.cache:/home/jovyan/.cache
            # - ./pip.conf:/etc/pip.conf
        # command: ""
        #   pip install -r /home/jovyan/ss/requirements.txt
        entrypoint:  
            - /bin/sh
            - -c
            - |
              jt -t onedork -f roboto -fs 14 -nfs 14 -tfs 14 -ofs 11
              jupyter lab --allow-root --ip=0.0.0.0 --no-browser
        restart: always

    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        command: redis-server --requirepass mypasswd
        ports :
            - 6379:6379
