version: '3'

services:
  taos:
    image: taos
    container_name: taos
    build: .
    restart: always
    ports:
      - 6020:6020
      - 6030:6030
      - 6035:6035
      - 6030-6039:6030-6039/udp
    volumes:
      - ./data:/data
      # - ./app:/app/
      - ./taos.cfg:/etc/taos/taos.cfg
    entrypoint:  
        - /bin/sh
        - -c
        - |
          cd /app/TDengine/build && build && cmake ../TDengine && cmake --build . 
          cp /app/build/build/bin/* /app/
          /app/taosd -c /etc/taos
    stdin_open: true
    tty: true